# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shohei Takaoa"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sh.takaoka.91@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""
resume_header_contact_info:     "XXXXX, St Petersburg, Florida 33705 • sh.takaoka.91@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>A postdoctoral researcher with specialization in molecular biology and bioinformatics. I was working on a project which connects dysregulation of RNA decay in the brain and obesity during my PhD. After I got PhD, I worked at pharmaceutical company as a bioinformatician and experienced analyzing varieties of NGS datasets including RNA-seq, scRNA-seq, Spatial transcriptomics, WGS, etc.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_publicaions:     true
resume_section_presentations:   true
resume_section_skills:          true
resume_section_links:           false
resume_section_recognition:     false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/stakaoka0"
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/s-takaoka-8727ab120/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://stakaoka0.github.io/"
  # resume_medium_url:            "https://medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
